controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Category;
use app\models\Product;
use app\models\User;
use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{

    /**
     * @var string имя шаблона для страниц данного контроллера
     */
//    public $layout = '';

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * My very first page in Yii
     * @return string
     */
    public function actionPage() {
        $text = 'This is content of page. Let me be in DB.';
        return $this->render('page', [
            'text' => $text,
        ]);
    }

    public function actionProduct(int $id) {
        $product = Product::find()->where(['id' => $id])->one();

        if (!$product) {
            throw new NotFoundHttpException('404');
        }
        return $this->render('product', [
            'product' => $product,
        ]);
    }

    public function actionProductList(?int $id = NULL) : string {
        $products = $id ? Product::find()->where(['category_id' => $id]) : Product::find();
//        $products = Product::find();
        $categories = Category::find()->all();

        $countProducts = clone $products;

        $pages = new Pagination(['totalCount' => $countProducts->count(), 'defaultPageSize' => 1]);
        $products = $products->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        return $this->render('product-list', [
            'products' => $products,
            'categories' => $categories,
            'pages' => $pages
        ]);
    }

    public function actionSingUp() {

        $user = new User();

        if ($user->load(Yii::$app->request->post())) {

            $user->setPassword($user->password);
            $user->save();

            $role = Yii::$app->authManager->getRole('client');
            Yii::$app->authManager->assign($role, $user->id);

            return $this->redirect(['site/login']);
        }

        return $this->render('sign-up', [
            'user' => $user,
        ]);
    }

//    public function actionRoles() {
//        $adminRole = Yii::$app->authManager->createRole('admin');
//        Yii::$app->authManager->add($adminRole);
//        $clientRole = Yii::$app->authManager->createRole('client');
//        Yii::$app->authManager->add($clientRole);
//        $managerRole = Yii::$app->authManager->createRole('manager');
//        Yii::$app->authManager->add($managerRole);

        // привязываем роль админа к пользователю 1:
//        $adminRole = Yii::$app->authManager->getRole('admin');
//
//        $user = User::findOne(1);
//
//        Yii::$app->authManager->assign($adminRole, $user->id);
//    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use app\assets\AppAsset;
use yii\helpers\Url;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <!-- Custom Theme files -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Wedding Store Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- /start menu -->
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>


<!--header-->
<div class="top_bg">
    <div class="container">
        <div class="header_top-sec">
            <div class="top_right">
                <ul>
                    <li><a href="#">help</a></li>|
                    <li><a href="contact.html">Contact</a></li>|
                    <li><a href="login.html">Track Order</a></li>
                </ul>
            </div>
            <div class="top_left">
                <ul>
                    <?php if (Yii::$app->user->isGuest) { ?>
                        <li class="top_link"><a href="<?= Url::to(['site/sing-up']) ?>">Зарегистрироваться</a></li>|
                        <li class="top_link"><a href="<?= Url::to(['site/login']) ?>">Войти</a></li>
                    <?php } else { ?>
                        <li class="top_link"><?= Yii::$app->user->identity->first_name ?></li>|
                        <li class="top_link"><a href="<?= Url::to(['site/logout']) ?>">Выйти</a></li>
                    <?php } ?>
                </ul>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>
<div class="header-top">
    <div class="header-bottom">
        <div class="container">
            <div class="logo">
                <a href="index.html"><h1>Wedding Store</h1></a>
            </div>
            <!---->

            <div class="top-nav">
                <ul class="memenu skyblue"><li class="active"><a href="index.html">Home</a></li>
                    <li class="grid"><a href="#">Wedding</a>
                        <div class="mepanel">
                            <div class="row">
                                <div class="col1 me-one">
                                    <h4>Shop</h4>
                                    <ul>
                                        <li><a href="product.html">New Arrivals</a></li>
                                        <li><a href="product.html">Men</a></li>
                                        <li><a href="product.html">Women</a></li>
                                        <li><a href="product.html">Accessories</a></li>
                                        <li><a href="product.html">Kids</a></li>
                                        <li><a href="login.html">login</a></li>
                                        <li><a href="product.html">Brands</a></li>
                                        <li><a href="product.html">My Shopping Bag</a></li>
                                    </ul>
                                </div>
                                <div class="col1 me-one">
                                    <h4>Style Zone</h4>
                                    <ul>
                                        <li><a href="product.html">Men</a></li>
                                        <li><a href="product.html">Women</a></li>
                                        <li><a href="product.html">Brands</a></li>
                                        <li><a href="product.html">Kids</a></li>
                                        <li><a href="product.html">Accessories</a></li>
                                        <li><a href="product.html">Style Videos</a></li>
                                    </ul>
                                </div>
                                <div class="col1 me-one">
                                    <h4>Popular Brands</h4>
                                    <ul>
                                        <li><a href="product.html">Levis</a></li>
                                        <li><a href="product.html">Persol</a></li>
                                        <li><a href="product.html">Nike</a></li>
                                        <li><a href="product.html">Edwin</a></li>
                                        <li><a href="product.html">New Balance</a></li>
                                        <li><a href="product.html">Jack & Jones</a></li>
                                        <li><a href="product.html">Paul Smith</a></li>
                                        <li><a href="product.html">Ray-Ban</a></li>
                                        <li><a href="product.html">Wood Wood</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="grid"><a href="#">Bride Style</a>
                        <div class="mepanel">
                            <div class="row">
                                <div class="col1 me-one">
                                    <h4>Shop</h4>
                                    <ul>
                                        <li><a href="product.html">New Arrivals</a></li>
                                        <li><a href="product.html">Men</a></li>
                                        <li><a href="product.html">Women</a></li>
                                        <li><a href="product.html">Accessories</a></li>
                                        <li><a href="product.html">Kids</a></li>
                                        <li><a href="login.html">login</a></li>
                                        <li><a href="product.html">Brands</a></li>
                                        <li><a href="product.html">My Shopping Bag</a></li>
                                    </ul>
                                </div>
                                <div class="col1 me-one">
                                    <h4>Style Zone</h4>
                                    <ul>
                                        <li><a href="product.html">Men</a></li>
                                        <li><a href="product.html">Women</a></li>
                                        <li><a href="product.html">Brands</a></li>
                                        <li><a href="product.html">Kids</a></li>
                                        <li><a href="product.html">Accessories</a></li>
                                        <li><a href="product.html">Style Videos</a></li>
                                    </ul>
                                </div>
                                <div class="col1 me-one">
                                    <h4>Popular Brands</h4>
                                    <ul>
                                        <li><a href="product.html">Levis</a></li>
                                        <li><a href="product.html">Persol</a></li>
                                        <li><a href="product.html">Nike</a></li>
                                        <li><a href="product.html">Edwin</a></li>
                                        <li><a href="product.html">New Balance</a></li>
                                        <li><a href="product.html">Jack & Jones</a></li>
                                        <li><a href="product.html">Paul Smith</a></li>
                                        <li><a href="product.html">Ray-Ban</a></li>
                                        <li><a href="product.html">Wood Wood</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="grid"><a href="typo.html">Typo</a></li>
                    <li class="grid"><a href="contact.html">Contact</a></li>
                </ul>
                <div class="clearfix"> </div>
            </div>
            <!---->
            <div class="cart box_1">
                <a href="checkout.html">
                    <h3> <div class="total">
                            <span class="simpleCart_total"></span> (<span id="simpleCart_quantity" class="simpleCart_quantity"></span>)</div>
                        <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span></h3>
                </a>
                <p><a href="javascript:;" class="simpleCart_empty">Empty Cart</a></p>
                <div class="clearfix"> </div>
            </div>
            <div class="clearfix"> </div>
            <!---->
        </div>
        <div class="clearfix"> </div>
    </div>
</div>

<?= Alert::widget() ?>
<?= $content ?>

<!---->
<div class="shoping">
    <div class="container">
        <div class="shpng-grids">
            <div class="col-md-4 shpng-grid">
                <h3>Free Shipping</h3>
                <p>On Order Over Rs999</p>
            </div>
            <div class="col-md-4 shpng-grid">
                <h3>Order Return</h3>
                <p>Return Within 14days</p>
            </div>
            <div class="col-md-4 shpng-grid">
                <h3>COD</h3>
                <p>Cash On Delivery</p>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<!---->
<div class="footer">
    <div class="container">
        <div class="ftr-grids">
            <div class="col-md-3 ftr-grid">
                <h4>About Us</h4>
                <ul>
                    <li><a href="#">Who We Are</a></li>
                    <li><a href="contact.html">Contact Us</a></li>
                    <li><a href="#">Our Sites</a></li>
                    <li><a href="#">In The News</a></li>
                    <li><a href="#">Team</a></li>
                    <li><a href="#">Careers</a></li>
                </ul>
            </div>
            <div class="col-md-3 ftr-grid">
                <h4>Customer service</h4>
                <ul>
                    <li><a href="#">FAQ</a></li>
                    <li><a href="#">Shipping</a></li>
                    <li><a href="#">Cancellation</a></li>
                    <li><a href="#">Returns</a></li>
                    <li><a href="#">Bulk Orders</a></li>
                    <li><a href="#">Buying Guides</a></li>
                </ul>
            </div>
            <div class="col-md-3 ftr-grid">
                <h4>Your account</h4>
                <ul>
                    <li><a href="account.html">Your Account</a></li>
                    <li><a href="#">Personal Information</a></li>
                    <li><a href="#">Addresses</a></li>
                    <li><a href="#">Discount</a></li>
                    <li><a href="#">Track your order</a></li>
                </ul>
            </div>
            <div class="col-md-3 ftr-grid">
                <h4>Categories</h4>
                <ul>
                    <li><a href="#">> Wedding</a></li>
                    <li><a href="#">> Jewellerys</a></li>
                    <li><a href="#">> Shoes</a></li>
                    <li><a href="#">> Flowers</a></li>
                    <li><a href="#">> Cakes</a></li>
                    <li><a href="#">...More</a></li>
                </ul>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<!---->
<div class="copywrite">
    <div class="container">
        <p>Copyright © 2015 Wedding Store. All Rights Reserved | Design by <a href="http://w3layouts.com">W3layouts</a></p>
    </div>
</div>

<?php $this->endBody() ?>
<script>$(document).ready(function(){$(".memenu").memenu();});</script>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main_bckp.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>