controllers/CartController.php
<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 02.06.2018
 * Time: 12:39
 */

namespace app\controllers;

use app\models\Order;
use app\models\OrderProduct;
use app\models\Product;
use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;

class CartController extends Controller
{
    public function actionAdd() {
        if (\Yii::$app->request->isAjax) {
            $prodId = \Yii::$app->request->post('prodId');
            $quantity = \Yii::$app->request->post('quantity');

            $cart = \Yii::$app->session->get('cart') ?: [];

            if (in_array($prodId, array_keys($cart))) {
                $cart[$prodId] = $cart[$prodId] + $quantity;
            } else {
                $cart[$prodId] = $quantity;
            }

            \Yii::$app->session->set('cart', $cart);

            \Yii::$app->response->format = Response::FORMAT_JSON;

            return $cart;
        }

        throw new NotFoundHttpException('Доступ запрещён', 404);
    }

    public function actionShow() {
        if (\Yii::$app->request->isGet) {

            $cart = unserialize(\Yii::$app->session->get('cart'));
            var_dump($cart);

        }
        \Yii::$app->response->format = Response::FORMAT_JSON;
    }

    public function actionIndex()
    {
        $cart = \Yii::$app->session->get('cart') ?: [];
        $prodIds = array_keys($cart);
        $products = Product::find()->where(['in', 'id', $prodIds])->all();
        return $this->render('view', [
            'products' => $products,
            'cart' => $cart
        ]);
    }

    public function actionComplete() {
        $cart = \Yii::$app->session->get('cart') ?: [];
        $order = new Order();

        if (Yii::$app->request->isPost && $order->load(Yii::$app->request->post())) {
            $prodIds = array_keys($cart);
            $products = Product::find()->where(['in', 'id', $prodIds])->all();
            $sum = 0;
            foreach ($products as $product) {
                $sum += $product->price * $cart[$product->id];
            }
            $order->summ = $sum;
            $order->user_id = Yii::$app->user->id;
            Yii::$app->session->remove('cart');

            $order->save();

            foreach ($cart as $key => $item) {
                (new OrderProduct([
                    'order_id' => $order->id,
                    'product_id' => $key,
                    'count' => $item,
                ]))->save();
            }
        }

        return $this->render('complete', [
            'order' => $order,
//            'cart' => $cart
        ]);
    }
//
//    public function actionView2()
//    {
//        \Yii::$app->session->addFlash('info', 'ololo');
//        \Yii::$app->session->addFlash('info2', 'ololo');
//        \Yii::$app->session->addFlash('info', 'ololo');
//        \Yii::$app->session->removeFlash('info');
//
//        return $this->render('view2');
//    }

}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Category;
use app\models\Product;
use app\models\User;
use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{

    /**
     * @var string имя шаблона для страниц данного контроллера
     */
//    public $layout = '';

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * My very first page in Yii
     * @return string
     */
    public function actionPage() {
        $text = 'This is content of page. Let me be in DB.';
        return $this->render('page', [
            'text' => $text,
        ]);
    }

    public function actionProduct(int $id) {
        $product = Product::find()->where(['id' => $id])->one();

        if (!$product) {
            throw new NotFoundHttpException('404');
        }
        return $this->render('product', [
            'product' => $product,
        ]);
    }

    public function actionProductList(?int $id = NULL) : string {
        $products = $id ? Product::find()->where(['category_id' => $id]) : Product::find();
//        $products = Product::find();
        $categories = Category::find()->all();

        $countProducts = clone $products;

        $pages = new Pagination(['totalCount' => $countProducts->count(), 'defaultPageSize' => 1]);
        $products = $products->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        return $this->render('product-list', [
            'products' => $products,
            'categories' => $categories,
            'pages' => $pages
        ]);
    }

    public function actionSingUp() {

        $user = new User();

        if ($user->load(Yii::$app->request->post())) {

            $user->setPassword($user->password);
            $user->save();

            $role = Yii::$app->authManager->getRole('client');
            Yii::$app->authManager->assign($role, $user->id);

            return $this->redirect(['site/login']);
        }

        return $this->render('sign-up', [
            'user' => $user,
        ]);
    }

//    public function actionRoles() {
//        $adminRole = Yii::$app->authManager->createRole('admin');
//        Yii::$app->authManager->add($adminRole);
//        $clientRole = Yii::$app->authManager->createRole('client');
//        Yii::$app->authManager->add($clientRole);
//        $managerRole = Yii::$app->authManager->createRole('manager');
//        Yii::$app->authManager->add($managerRole);

        // привязываем роль админа к пользователю 1:
//        $adminRole = Yii::$app->authManager->getRole('admin');
//
//        $user = User::findOne(1);
//
//        Yii::$app->authManager->assign($adminRole, $user->id);
//    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Hi, noobs!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/page.php
<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 19.05.2018
 * Time: 14:20
 *
 * @var string $text переменная с контентом
 */
?>
<h1>Hi there!</h1>
<?php
echo $text;

views/site/product-list.php
<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 31.05.2018
 * Time: 18:46
 *
 * @var array $products
 * @var array $categories
 */
use yii\helpers\Url;
use yii\widgets\LinkPager;

?>
<div class="product-model">
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li class="active">Products</li>
        </ol>
        <h2>Our Products</h2>
        <div class="col-md-3">
            <ul>
            <?php foreach ($categories as $category) { ?>
                <li><a href="<?= Url::to(['/site/product-list', 'id' => $category->id]) ?>"><?= $category->name ?></a></li>
            <?php } ?>
            </ul>
        </div>
        <div class="col-md-9 product-model-sec">
            <?php foreach ($products as $product) { ?>
                <div class="product-grid love-grid">
                    <a href="<?= Url::to(['/site/product', 'id' => $product->id]); ?>">
                        <div class="more-product"><span> </span></div>
                        <div class="product-img b-link-stripe b-animate-go  thickbox">
                            <img src="<?= $product->image ?>" class="img-responsive" alt=""/>
                            <div class="b-wrapper">
                                <h4 class="b-animate b-from-left  b-delay03">
                                    <button class="btns"><span class="glyphicon glyphicon-zoom-in" aria-hidden="true"></span>Quick View</button>
                                </h4>
                            </div>
                        </div>
                    </a>
                    <div class="product-info simpleCart_shelfItem">
                        <div class="product-info-cust prt_name">
                            <h4><?= $product->name ?></h4>
                            <?php if (Yii::$app->user->can('admin')) { ?>
                                <p>ID: <?= $product->id ?></p>
                            <?php } ?>
                            <span class="item_price">$<?= $product->price ?></span>
                            <input type="text" class="item_quantity" value="1" />
                            <input type="button" class="item_add items" value="ADD" data-prod-id="<?= $product->id ?>"
                                   data-url="<?= Url::to(['cart/add'])?>">
                        </div>
                        <div class="clearfix"> </div>
                    </div>
                </div>
            <?php } ?>
        </div>
        <div class="row"><?= LinkPager::widget([
                'pagination' => $pages,
            ]); ?></div>
<div class="rsidebar span_1_of_left">
    <section  class="sky-form">
        <div class="product_right">
            <?= \app\widgets\Menu::widget(['message' => 'Менюшка']); ?>
            <h4 class="m_2"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span>Categories</h4>
            <div class="tab1">
                <ul class="place">
                    <li class="sort">Fashion</li>
                    <li class="by"><img src="images/do.png" alt=""></li>
                    <div class="clearfix"> </div>
                </ul>
                <div class="single-bottom">
                    <a href="#"><p>Gifts</p></a>
                    <a href="#"><p>Flowers</p></a>
                    <a href="#"><p>Shoes</p></a>
                    <a href="#"><p>Suits</p></a>
                    <a href="#"><p>Dresses</p></a>
                </div>
            </div>
            <div class="tab2">
                <ul class="place">
                    <li class="sort">Women Ethnic Wear</li>
                    <li class="by"><img src="images/do.png" alt=""></li>
                    <div class="clearfix"> </div>
                </ul>
                <div class="single-bottom">
                    <a href="#"><p>Sarees & More</p></a>
                    <a href="#"><p>Salwar Suits</p></a>
                </div>
            </div>
            <div class="tab3">
                <ul class="place">
                    <li class="sort">Personal Care</li>
                    <li class="by"><img src="images/do.png" alt=""></li>
                    <div class="clearfix"> </div>
                </ul>
                <div class="single-bottom">
                    <a href="#"><p>Make Up</p></a>
                </div>
            </div>
            <div class="tab4">
                <ul class="place">
                    <li class="sort">Jewellery</li>
                    <li class="by"><img src="images/do.png" alt=""></li>
                    <div class="clearfix"> </div>
                </ul>
                <div class="single-bottom">
                    <a href="#"><p>Fashion</p></a>
                    <a href="#"><p>Precious</p></a>
                    <a href="#"><p>1 Gram Gold</p></a>
                </div>
            </div>
            <div class="tab5">
                <ul class="place">
                    <li class="sort">Specials</li>
                    <li class="by"><img src="images/do.png" alt=""></li>
                    <div class="clearfix"> </div>
                </ul>
                <div class="single-bottom">
                    <a href="#"><p>Cakes</p></a>
                    <a href="#"><p>Party Items</p></a>
                    <a href="#"><p></p></a>
                    <a href="#"><p>Relax Chairs</p></a>
                </div>
            </div>

            <!--script-->
            <script>
                $(document).ready(function(){
                    $(".tab1 .single-bottom").hide();
                    $(".tab2 .single-bottom").hide();
                    $(".tab3 .single-bottom").hide();
                    $(".tab4 .single-bottom").hide();
                    $(".tab5 .single-bottom").hide();

                    $(".tab1 ul").click(function(){
                        $(".tab1 .single-bottom").slideToggle(300);
                        $(".tab2 .single-bottom").hide();
                        $(".tab3 .single-bottom").hide();
                        $(".tab4 .single-bottom").hide();
                        $(".tab5 .single-bottom").hide();
                    })
                    $(".tab2 ul").click(function(){
                        $(".tab2 .single-bottom").slideToggle(300);
                        $(".tab1 .single-bottom").hide();
                        $(".tab3 .single-bottom").hide();
                        $(".tab4 .single-bottom").hide();
                        $(".tab5 .single-bottom").hide();
                    })
                    $(".tab3 ul").click(function(){
                        $(".tab3 .single-bottom").slideToggle(300);
                        $(".tab4 .single-bottom").hide();
                        $(".tab5 .single-bottom").hide();
                        $(".tab2 .single-bottom").hide();
                        $(".tab1 .single-bottom").hide();
                    })
                    $(".tab4 ul").click(function(){
                        $(".tab4 .single-bottom").slideToggle(300);
                        $(".tab5 .single-bottom").hide();
                        $(".tab3 .single-bottom").hide();
                        $(".tab2 .single-bottom").hide();
                        $(".tab1 .single-bottom").hide();
                    })
                    $(".tab5 ul").click(function(){
                        $(".tab5 .single-bottom").slideToggle(300);
                        $(".tab4 .single-bottom").hide();
                        $(".tab3 .single-bottom").hide();
                        $(".tab2 .single-bottom").hide();
                        $(".tab1 .single-bottom").hide();
                    })
                });
            </script>
            <!-- script -->
    </section>
    <section  class="sky-form">
        <h4><span class="glyphicon glyphicon-minus" aria-hidden="true"></span>DISCOUNTS</h4>
        <div class="row row1 scroll-pane">
            <div class="col col-4">
                <label class="checkbox"><input type="checkbox" name="checkbox" checked=""><i></i>Upto - 10% (20)</label>
            </div>
            <div class="col col-4">
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>40% - 50% (5)</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>30% - 20% (7)</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>10% - 5% (2)</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Other(50)</label>
            </div>
        </div>
    </section>
    <section  class="sky-form">
        <h4><span class="glyphicon glyphicon-minus" aria-hidden="true"></span>Price</h4>
        <ul class="dropdown-menu1">
            <li><a href="">
                    <div id="slider-range"></div>
                    <input type="text" id="amount" style="border: 0; font-weight: NORMAL;   font-family: 'Arimo', sans-serif;" />
                </a></li>
        </ul>
    </section>
    <!---->
    <script type="text/javascript" src="js/jquery-ui.min.js"></script>
    <link rel="stylesheet" type="text/css" href="css/jquery-ui.css">
    <script type='text/javascript'>//<![CDATA[
        $(window).load(function(){
            $( "#slider-range" ).slider({
                range: true,
                min: 0,
                max: 400000,
                values: [ 8500, 350000 ],
                slide: function( event, ui ) {  $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] );
                }
            });
            $( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) + " - $" + $( "#slider-range" ).slider( "values", 1 ) );

        });//]]>
    </script>
    <!---->
    <section  class="sky-form">
        <h4><span class="glyphicon glyphicon-minus" aria-hidden="true"></span>Type</h4>
        <div class="row row1 scroll-pane">
            <div class="col col-4">
                <label class="checkbox"><input type="checkbox" name="checkbox" checked=""><i></i>1 Gram Gold (30)</label>
            </div>
            <div class="col col-4">
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Gold Plated   (30)</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Platinum      (30)</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Silver        (30)</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Jewellery Sets  (30)</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Stone Items   (30)</label>
            </div>
        </div>
    </section>
    <section  class="sky-form">
        <h4><span class="glyphicon glyphicon-minus" aria-hidden="true"></span>Brand</h4>
        <div class="row row1 scroll-pane">
            <div class="col col-4">
                <label class="checkbox"><input type="checkbox" name="checkbox" checked=""><i></i>Akasana Collectio</label>
            </div>
            <div class="col col-4">
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Colori</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Crafts Hub</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Jisha</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Karatcart</label>
                <label class="checkbox"><input type="checkbox" name="checkbox" ><i></i>Titan</label>
                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>Amuktaa</label>
            </div>
        </div>
    </section>
</div>
</div>
</div>
</div>

views/site/sign-up.php
<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 02.06.2018
 * Time: 14:47
 *
 * @var $user \app\models\User
 */
use yii\bootstrap\ActiveForm;

?>
<div class="container">
    <h1>Регистрация пользователя</h1>
    <?php $form = ActiveForm::begin(); ?>
    <?= $form->field($user, 'first_name')->input('string'); ?>
    <?= $form->field($user, 'last_name')->input('string'); ?>
    <?= $form->field($user, 'email')->input('email'); ?>
    <?= $form->field($user, 'password')->passwordInput(); ?>
    <button type="submit" class="btn btn-sm btn-success">Регистрация</button>
    <?php ActiveForm::end(); ?>
</div>

views/site/test-form.php
<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 24.05.2018
 * Time: 18:40
 *
 * @var \app\models\Product $product
 * @var \app\models\Category $category
 */
use yii\widgets\ActiveForm;

?>
<div class="container">
    <?php $form = ActiveForm::begin(); ?>
        <?= $form->field($product, 'name')->textInput([
//            'class' => 'custom-class',
//            'id' => 'custom-id',
//            'something' => 'custom-something',
        ]) ?>
        <?= $form->field($category, 'name')->textInput(['placeholder' => 'some text await']) ?>
        <?= $form->field($product, 'title')->textInput() ?>
        <?= $form->field($product, 'description')->textarea() ?>
        <input type="submit" value="Сабмит">
    <?php ActiveForm::end(); ?>
</div>